# Generated by Django 5.0.3 on 2024-03-24 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('trip_photo', models.ImageField(default='trip_photos/default_photo.jpg', upload_to='trip_photos/')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_of_trip', models.DateField()),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
